id: ID6A49BD9
legacy_id: P009106
ocr_import_info:
  bdrc_scan_id: W00KG01658
  source: bdrc
  ocr_info:
    timestamp: '2020-03-21T22:57:17'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-29T11:38:58.593660+00:00'
last_modified: 2022-08-29 19:39:14.813979
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W00KG01658
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW00KG01658
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: སྨྲ་བ་ངན་པ་རྣམ་པར་འཐག་པ་མི་ཤིགས་རྡོ་རྗེའི་ཐོག་མདའ
  author: རྡོ་སྦིས་དགེ་བཤེས་ཤེས་རབ་རྒྱ་མཚོ།
statistics:
  ocr_word_mean_confidence_index: 0.9363961868681829
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I00KG02975:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00KG02975
      total_pages: 50
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I00KG02975.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9363961868681829
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
